/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/viki/ROSWS/simws/src/tum_simulator/cvg_sim_gazebo_plugins/srv/SetBias.srv
 *
 */


#ifndef CVG_SIM_GAZEBO_PLUGINS_MESSAGE_SETBIAS_H
#define CVG_SIM_GAZEBO_PLUGINS_MESSAGE_SETBIAS_H

#include <ros/service_traits.h>


#include <cvg_sim_gazebo_plugins/SetBiasRequest.h>
#include <cvg_sim_gazebo_plugins/SetBiasResponse.h>


namespace cvg_sim_gazebo_plugins
{

struct SetBias
{

typedef SetBiasRequest Request;
typedef SetBiasResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBias
} // namespace cvg_sim_gazebo_plugins


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cvg_sim_gazebo_plugins::SetBias > {
  static const char* value()
  {
    return "af1f260075d9ba9bd73ca10c6a45df07";
  }

  static const char* value(const ::cvg_sim_gazebo_plugins::SetBias&) { return value(); }
};

template<>
struct DataType< ::cvg_sim_gazebo_plugins::SetBias > {
  static const char* value()
  {
    return "cvg_sim_gazebo_plugins/SetBias";
  }

  static const char* value(const ::cvg_sim_gazebo_plugins::SetBias&) { return value(); }
};


// service_traits::MD5Sum< ::cvg_sim_gazebo_plugins::SetBiasRequest> should match 
// service_traits::MD5Sum< ::cvg_sim_gazebo_plugins::SetBias > 
template<>
struct MD5Sum< ::cvg_sim_gazebo_plugins::SetBiasRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cvg_sim_gazebo_plugins::SetBias >::value();
  }
  static const char* value(const ::cvg_sim_gazebo_plugins::SetBiasRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cvg_sim_gazebo_plugins::SetBiasRequest> should match 
// service_traits::DataType< ::cvg_sim_gazebo_plugins::SetBias > 
template<>
struct DataType< ::cvg_sim_gazebo_plugins::SetBiasRequest>
{
  static const char* value()
  {
    return DataType< ::cvg_sim_gazebo_plugins::SetBias >::value();
  }
  static const char* value(const ::cvg_sim_gazebo_plugins::SetBiasRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cvg_sim_gazebo_plugins::SetBiasResponse> should match 
// service_traits::MD5Sum< ::cvg_sim_gazebo_plugins::SetBias > 
template<>
struct MD5Sum< ::cvg_sim_gazebo_plugins::SetBiasResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cvg_sim_gazebo_plugins::SetBias >::value();
  }
  static const char* value(const ::cvg_sim_gazebo_plugins::SetBiasResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cvg_sim_gazebo_plugins::SetBiasResponse> should match 
// service_traits::DataType< ::cvg_sim_gazebo_plugins::SetBias > 
template<>
struct DataType< ::cvg_sim_gazebo_plugins::SetBiasResponse>
{
  static const char* value()
  {
    return DataType< ::cvg_sim_gazebo_plugins::SetBias >::value();
  }
  static const char* value(const ::cvg_sim_gazebo_plugins::SetBiasResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CVG_SIM_GAZEBO_PLUGINS_MESSAGE_SETBIAS_H
